In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
irdata = pd.read_csv('iris_data.txt', sep=",", header=None)
irdata.columns = ["sepal length in cm", "sepal width in cm", "petal length in cm", "petal width in cm", "class"]

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X = irdata[['sepal length in cm', 'sepal width in cm', 'petal length in cm', 'petal width in cm']]
y = irdata['class']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [6]:
from sklearn.svm import SVC

In [7]:
svc_model = SVC()

In [8]:
svc_model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
predictions = svc_model.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix,classification_report

In [11]:
print(confusion_matrix(y_test,predictions))

[[16  0  0]
 [ 0 12  1]
 [ 0  0 21]]


In [12]:
print(classification_report(y_test,predictions))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.95      1.00      0.98        21

    avg / total       0.98      0.98      0.98        50

